### ISSUE TITLE
Stage Installation Window Issues

### ISSUE THREAD

**Issue by PGames09** [Inferno214221/cmc-mod-manager#13]
The Stage Installation window is not completely visible, which prevents you from continuing with the process.
The window is not resizable so you cannot try resizing the window to try to fix the problem.
I am using the latest Pre-Release Version (auto).
![Captura de pantalla 2024-09-01 204736](https://github.com/user-attachments/assets/46b2e46a-8f01-4d79-80ba-8d4bf97afdb0)

**Comment by PGames09** [comment]
Also happens with Character Installation windows
![imagen](https://github.com/user-attachments/assets/08b30bb0-943a-410a-ac38-5a9d948555ca)

**Comment by Inferno214221** [comment]
Thanks for submitting a bug report, this appears to be similar to (if not an occurrence of #4), which you were involved with previously. I swear I have fixed this bug three or four times already, but its obviously still occurring so I'll look into it again.

I will move this issue back to #4 if thats okay, because I believe them to be the same bug.

As a side note: Thanks for testing the latest version, however `auto` is the automatically generated build of main and is not guaranteed to be stable. I would heavily recommend against using this version, but rather the latest named pre-release.
